/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rcorrent.views.edit;

import com.rcorrent.dao.GenericDAO;
import com.rcorrent.models.Bird;
import com.rcorrent.models.DogCat;
import com.rcorrent.models.Owner;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author rcorrent
 */
public class PetEditView extends javax.swing.JDialog {
    
    private Integer ownerId;
    
    private DogCat dogCat;
    private Bird bird;
    private final GenericDAO genericDao = new GenericDAO();

    /**
     * Creates new form PetView
     */
    public PetEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        /* Initializing button's state*/
        initialState();
    }
    
    public PetEditView(java.awt.Frame parent, boolean modal, Integer ownerId) {
        super(parent, modal);
        this.ownerId = ownerId;
        initComponents();
        
        /* Initializing button's state*/
        initialState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpPet = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jtpRegisterPet = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jrbDogCat = new javax.swing.JRadioButton();
        jrbBird = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtfDCHeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDCBreed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDCHairType = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfBWingSize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfBColor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfPetName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfPetAge = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtfValue = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGrpPet.add(jrbDogCat);
        jrbDogCat.setText("Dog - Cat");
        jrbDogCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDogCatActionPerformed(evt);
            }
        });

        btnGrpPet.add(jrbBird);
        jrbBird.setText("Bird");
        jrbBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBirdActionPerformed(evt);
            }
        });

        jLabel4.setText("Height");

        jLabel5.setText("Breed");

        jLabel6.setText("Hair type");

        jLabel7.setText("Wing size");

        jLabel8.setText("Color");

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Delete");

        jLabel3.setText("Pet name");

        jLabel1.setText("Pet age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jtfDCBreed, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jtfDCHairType)
                                .addComponent(jrbDogCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtfDCHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfBWingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrbBird)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(127, 127, 127))
                            .addComponent(jtfBColor)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfPetName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPetAge))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPetAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDogCat)
                    .addComponent(jrbBird))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDCHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBWingSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDCBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDCHairType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnDelete))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jtpRegisterPet.addTab("Register", jPanel1);

        jButton2.setText("Search");

        jButton3.setText("New");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpRegisterPet.addTab("Search", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpRegisterPet)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpRegisterPet)
        );

        setSize(new java.awt.Dimension(555, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        if(getPet()){
            if(jrbDogCat.isSelected()){
                genericDao.save(this.dogCat);
                JOptionPane.showMessageDialog(null, "Dog-Cat Saved Successfully!!" );
            }else{
                genericDao.save(this.bird);
                JOptionPane.showMessageDialog(null, "Bird Saved Successfully!!" );
                
            }            
            this.dispose();
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jrbDogCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDogCatActionPerformed
        if(jrbDogCat.isSelected()){
            selectDogCat(true);
            selectBird(false);
        }else{
            selectDogCat(false);
        }
    }//GEN-LAST:event_jrbDogCatActionPerformed

    private void jrbBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBirdActionPerformed
        if(jrbBird.isSelected()){
            selectBird(true);
            selectDogCat(false);
        }else{
            selectBird(false);
        }
    }//GEN-LAST:event_jrbBirdActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               PetEditView dialog = new PetEditView(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpPet;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JRadioButton jrbBird;
    private javax.swing.JRadioButton jrbDogCat;
    private javax.swing.JTextField jtfBColor;
    private javax.swing.JTextField jtfBWingSize;
    private javax.swing.JTextField jtfDCBreed;
    private javax.swing.JTextField jtfDCHairType;
    private javax.swing.JTextField jtfDCHeight;
    private javax.swing.JTextField jtfPetAge;
    private javax.swing.JTextField jtfPetName;
    private javax.swing.JTextField jtfValue;
    private javax.swing.JTabbedPane jtpRegisterPet;
    // End of variables declaration//GEN-END:variables
    
    
    public Boolean getPet(){
                
        Owner owner = new Owner();
        owner = (Owner) genericDao.getById(Owner.class, ownerId);
        
        String petName = jtfPetName.getText();
        String petAge = jtfPetAge.getText();
        petName = petName.trim();
        petAge = petAge.trim();
                
        if(petName.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Pet's Name");
            jtfPetName.requestFocus();
            return false;
        }
        if(petAge.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Pet's Age");
            jtfPetAge.requestFocus();
            return false;
        }       
        
        if(jrbDogCat.isSelected()){
            
           
            DogCat dc = new DogCat();
            
            String height = jtfDCHeight.getText();
            String breed = jtfDCBreed.getText();
            String hairType = jtfDCHairType.getText();

            height = height.trim().replace(",", ".");
            breed = breed.trim();
            hairType = hairType.trim();

            try {
                dc.setHeight(Double.parseDouble(height));          
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Enter a valid Pet's Height");
                jtfDCHeight.requestFocus();
                return false;
            }
            if(breed.equals("")){
                JOptionPane.showMessageDialog(null, "Enter Pet's Breed");
                jtfDCBreed.requestFocus();
                return false;
            } 
            if(hairType.equals("")){
                JOptionPane.showMessageDialog(null, "Enter Pet's Hair Type");
                jtfDCHairType.requestFocus();
                return false;
            }
            
            
            
            dc.setNmPet(petName);
            dc.setAgePet(petAge);
            dc.setBreed(breed);
            dc.setHairType(hairType);
            
            dc.setOwner(owner);
            
            this.dogCat = dc;
            
        }
        
        if(jrbBird.isSelected()){
            
            Bird b = new Bird();
            
            String wingSize = jtfBWingSize.getText();
            String color = jtfBColor.getText();
            
            wingSize = wingSize.trim().replace(",", ".");
            color = color.trim();
            
            try {
                b.setWingSize(Double.parseDouble(wingSize));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Enter a valid Pet's Wing Size");
                jtfBWingSize.requestFocus();
                return false;
            }
            
            if(color.equals("")){
                JOptionPane.showMessageDialog(null, "Enter Pet's Color");
                jtfBColor.requestFocus();
                return false;
            }
            
            b.setNmPet(petName);
            b.setAgePet(petAge);
            b.setColor(color);
            
            b.setOwner(owner);
            
            this.bird = b;
        }
        return true;
    }

    public void selectDogCat(Boolean state){
        jtfDCHeight.setEnabled(state);
        jtfDCBreed.setEnabled(state);
        jtfDCHairType.setEnabled(state);
        
        jbtnSave.setEnabled(true);
    }
    
    public void selectBird(Boolean state){
        jtfBWingSize.setEnabled(state);
        jtfBColor.setEnabled(state);
        
        jbtnSave.setEnabled(true);
    }
    
    public void initialState(){
        jrbDogCat.setSelected(false);
        jrbBird.setSelected(false);
        selectDogCat(false);
        selectBird(false);
        jbtnDelete.setEnabled(false);
        jbtnSave.setEnabled(false);
    }
    
}
